// Localised copy for the interactive experience layer.
// Extracted from App.jsx.

export const EXPERIENCE_COPY = {
  zh: {
    commandOpen: "命令面板",
    commandPlaceholder: "搜索文章、项目、主题、背景或后台入口",
    commandEmpty: "没有匹配结果",
    archiveTitle: "时间档案",
    archiveBody: "把文章、项目和持续实验放进同一条时间轴里。",
    archiveOpen: "打开档案",
    pinnedTitle: "Pinned Spaces",
    pinnedBody: "把最想先被看到的内容固定在首页入口。",
    layoutTitle: "首页布局",
    layoutMagazine: "杂志流",
    layoutArchive: "档案流",
    layoutCards: "卡片流",
    readingRoom: "阅读室",
    focusMode: "专注",
    nightMode: "夜读",
    ambientMode: "环境音",
    readAloud: "朗读",
    stopReading: "停止朗读",
    footnotes: "脚注",
    timelineArticles: "文章",
    timelineProjects: "项目",
    pinnedEditorTitle: "固定空间",
    pinnedEditorBody: "把文章、项目、链接或音频固定到首页。",
    addPinnedSpace: "新增固定项",
    removePinnedSpace: "删除固定项",
    pinnedKind: "内容类型",
    pinnedArticle: "文章",
    pinnedProject: "项目",
    pinnedLink: "链接",
    pinnedAudio: "音频",
    pinnedLabel: "标题",
    pinnedBodyLabel: "说明",
    pinnedUrl: "链接地址",
    pinnedAudioTitle: "音频标题",
    pinnedAudioArtist: "音频作者",
    pinnedAudioSrc: "音频地址",
    pinnedTarget: "关联内容",
    footnotesEditor: "脚注",
    openCommand: "打开命令面板",
    recentAccess: "最近访问",
    quickActions: "快捷操作",
    createArticleQuick: "新建文章",
    createProjectQuick: "新建项目",
    highlightAction: "高亮此段",
    noteOnParagraph: "添加批注",
    saveNote: "保存批注",
    removeNote: "删除批注",
    notePlaceholder: "写下这一段的理解、待改点或延展想法",
    highlightedParagraphs: "高亮段落",
    favoriteParagraphs: "收藏段落",
    readingResume: "继续阅读",
    recentReading: "最近阅读",
    recentEditing: "最近编辑",
    quickTheme: "快速切主题",
    quickLanguage: "快速切语言",
    exportNotes: "导出批注",
    importNotesDraft: "批注已导入草稿",
    readingStats: "阅读统计",
    statsWords: "字数",
    statsParagraphs: "段落",
    statsNotes: "批注",
    statsFavorites: "收藏",
    archiveFilter: "筛选",
    archiveSearch: "搜索档案内容",
    archiveAllYears: "全部年份",
    archiveAllTags: "全部标签",
  },
  en: {
    commandOpen: "Command Palette",
    commandPlaceholder: "Search articles, projects, themes, backgrounds, or studio routes",
    commandEmpty: "No results found",
    archiveTitle: "Timeline Archive",
    archiveBody: "Place articles, projects, and ongoing experiments on one shared timeline.",
    archiveOpen: "Open Archive",
    pinnedTitle: "Pinned Spaces",
    pinnedBody: "Pin the content that should be discovered first on the homepage.",
    layoutTitle: "Home Layout",
    layoutMagazine: "Magazine",
    layoutArchive: "Archive",
    layoutCards: "Cards",
    readingRoom: "Reading Room",
    focusMode: "Focus",
    nightMode: "Night",
    ambientMode: "Ambient",
    readAloud: "Read Aloud",
    stopReading: "Stop Reading",
    footnotes: "Footnotes",
    timelineArticles: "Articles",
    timelineProjects: "Projects",
    pinnedEditorTitle: "Pinned Spaces",
    pinnedEditorBody: "Pin articles, projects, links, or audio modules to the homepage.",
    addPinnedSpace: "Add Pinned Space",
    removePinnedSpace: "Remove Item",
    pinnedKind: "Type",
    pinnedArticle: "Article",
    pinnedProject: "Project",
    pinnedLink: "Link",
    pinnedAudio: "Audio",
    pinnedLabel: "Title",
    pinnedBodyLabel: "Description",
    pinnedUrl: "Link URL",
    pinnedAudioTitle: "Audio Title",
    pinnedAudioArtist: "Audio Artist",
    pinnedAudioSrc: "Audio URL",
    pinnedTarget: "Target",
    footnotesEditor: "Footnotes",
    openCommand: "Open Command Palette",
    recentAccess: "Recent",
    quickActions: "Quick Actions",
    createArticleQuick: "New Article",
    createProjectQuick: "New Project",
    highlightAction: "Highlight",
    noteOnParagraph: "Annotate",
    saveNote: "Save Note",
    removeNote: "Remove Note",
    notePlaceholder: "Capture a thought, revision note, or follow-up idea for this paragraph",
    highlightedParagraphs: "Highlights",
    favoriteParagraphs: "Favorites",
    readingResume: "Resume Reading",
    recentReading: "Recent Reading",
    recentEditing: "Recent Editing",
    quickTheme: "Quick Theme",
    quickLanguage: "Quick Language",
    exportNotes: "Export Notes",
    importNotesDraft: "Notes imported into draft",
    readingStats: "Reading Stats",
    statsWords: "Words",
    statsParagraphs: "Paragraphs",
    statsNotes: "Notes",
    statsFavorites: "Favorites",
    archiveFilter: "Filters",
    archiveSearch: "Search archive content",
    archiveAllYears: "All Years",
    archiveAllTags: "All Tags",
  },
};

export function getExperienceCopy(language) {
  return EXPERIENCE_COPY[language] ? { ...EXPERIENCE_COPY.en, ...EXPERIENCE_COPY[language] } : EXPERIENCE_COPY.en;
}
